---
title: "Schedule"
---

## Week 1

### Monday 8-31


[Lecture Slides](lectures/8-31_Intro.pdf)

[Lecture Video](https://ensemble.reed.edu/Watch/a8F5TqQf)

#### Topics

- Course Logistics
- How old am I?
  - [Class data](data/how_old.csv) *Groups 1 - 6 were student groups, Group 7 estimates came from [how-old.net](https://how-old.net) and Group 8 are my estimates based on public data*

#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Review the syllabus

#### Due


- Complete Slack Introduction:
  1. Sign-in to our [Slack workspace](reedmath243fall2020.slack.com)
  2. Navigate to the #general-discussion channel using the menu on the left side of the screen and post a message with your name and three numeric values that describe yourself, two of which are true and one of which is false (don't say which is which).
  3. Find another person's post, hover over it, and click the chat bubble icon to start a thread. Then guess which of that person's three statements is false.
  4. Finally, find my name (Nate Wells) under Direct Messages on the left side of the screen, and send me a private message answering the following questions:
      a) What is your preferred name? (and what are your pronouns, if you'd like to share?)
      b) Do you have experience using R and Rstudio?
      c) What do you hope to take away from this course?
      d) What concerns do you have about this course, or about academics in general this term?
      e) What is one image that best describes you? (feel free to upload it) 




### Wednesday 9-2

[Lecture Slides](lectures/9-2_GitHub.pdf)

[Lecture Video](https://ensemble.reed.edu/Watch/g6SLd45D)

#### Topics

- RStudio

- GitHub
  - [Working Solo](https://github.com/Reed-Stat-Learning-Fall-2020/course-materials/raw/master/Activities/working_solo_github.pdf)

- GitHub Classroom

#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Chapter 1 and Section 2.1 (p 1-29) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)

- [Chapter 1](https://happygitwithr.com/big-picture.html) and [Chapter 4](https://happygitwithr.com/github-acct.html) in [Happy Git and GitHub for the useR](https://happygitwithr.com/)

#### Due

- Sign up for a [GitHub](https://github.com) account.

### Friday 9-4

[Lecture Slides](lectures/9-4_Estimating_f.pdf)


#### Topics

- Estimating $f$, the relationship between predictor and response variables

- Assessing error in the guess my age activity


#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Review Section 2.1 (p 15-29) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)

#### Due

- Homework 0. (Use the link in the #announcments channel to create your repo and view the assignment. Make sure you push any commits you make before 1:35pm on Friday.)


***********************************************



## Week 2

### Monday 9-7

No class; Labor Day



### Wednesday 9-9

[Lecture Slides](lectures/9-9_Assessing_Accuracy.pdf)

#### Topics

- Decomposing the Mean Squared Error
  
  - [Wednesday 9-9 Demo](files/demo_9-9.Rmd)

- The Bias-Variance Trade-off


#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Section 2.2 (p 29-41) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)

#### Assigned

- Homework 1 (Due Wednesday, 9/16 by the start of class)



### Friday 9-11

[Lecture Slides](lectures/9-11_SLR.pdf)

#### Topics

- Review Simple Linear Regression

- Introduction to Multiple Linear Regression


#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Section 3.1 (p 59-72) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)





**************************************************




## Week 3

### Monday 9-14

[Lecture Slides](lectures/9-14_MLR.pdf)

#### Topics
 

- Introduction to Multiple Linear Regression
  - [Regression plane for MLR](files/3d_scatterplot.html) [(.Rmd)](files/3d_scatterplot.Rmd)
- Assessing Accuracy of Linear Models
- Linear Models in R
  


#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Section 3.2 (p 71-82) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)

### Wednesday 9-16

[Lecture Slides](lectures/9-16_MLR_Accuracy.pdf)

#### Topics
 

- Extensions of the Linear Model


#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Section 3.3 (p 82-92) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)

#### Due

- Homework 1


#### Assigned

- Homework 2, To be posted by Wed. evening (Due Wednesday, 9/23 by the start of class)


### Friday 9-18

[Lecture Slides](lectures/9-18_MLR_Extensions.pdf)

#### Topics
 

- Extensions of the Linear Model
  - [Code from today's class](files/Demo_9-18.Rmd)


#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Section 3.3 (p 92-102) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)


**********************************************

## Week 4

### Monday 9-21

[Lecture Slides](lectures/9-21_MLR_Troubleshooting.pdf)

[Lecture Video](https://ensemble.reed.edu/Watch/t6MQf3q4) (requires Reed Kerberus credentials to watch)

#### Topics
 

- Troubleshooting linear models
  


#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Section 3.6 (p 109-119) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)

### Wednesday 9-23
 [Lecture Slides](lectures/9-23_MLR_Examples.pdf)
 
 [Lecture Video](https://ensemble.reed.edu/Watch/Ec79MyRr) (requires Reed Kerberus credentials to watch)

#### Topics
 

- Transformations


#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Section 3.5 (p 104-109) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)

#### Due

- Homework 2


#### Assigned

- No homework assigned.


### Friday 9-25


[Lecture Video](https://ensemble.reed.edu/Watch/Kp64Czj9)

#### Topics
 

- Review
  - [Midterm Practice](files/Midterm_1_Review.Rmd)

#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- None

**********************************************

## Week 5

### Monday 9-28

[Lecture Slides](lectures/9-28_KNN.pdf)  

[Lecture Video](https://ensemble.reed.edu/Watch/m5ZYj94N)

#### Topics
 

- KNN and Bayes Classifier
  
  - [Classification Activity](files/classification.Rmd)

#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Review Section 2.2.3 (p 37-42) and Section 3.5 (p 104-109) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)



### Wednesday 9-30

[Lecture Slides](lectures/9-30_LogisticReg.pdf)  

[Lecture Video](https://ensemble.reed.edu/Watch/Br5z9YLx)

#### Topics
 

- Logistic Regression

  - [3d Plot of Logistic function](files/Logistic_Example.html)


#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Section 4.1 - 4.3 (p 127-137) and Section 4.6.2 (p 156 - 160) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)

#### Due

- None


#### Assigned

- HW 3 assigned (Due Wednesday 10/7 by 1:35pm)


### Friday 9-25

[Lecture Slides](lectures/10-2_LogisticReg2.pdf)

[Lecture Video](https://ensemble.reed.edu/Watch/Fg9i4DXa)

#### Topics
 

-  More Logistic Regression 

  - [Titanic](data/titanic.csv)
  
  - [mushrooms](data/mushrooms.csv)

#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Section 12.1 - 12.2 (p 275 - 287) in [Applied Predictive Modeling](https://link-springer-com.proxy.library.reed.edu/book/10.1007%2F978-1-4614-6849-3) 



**********************************************

## Week 6



### Monday 10-5

[Lecture Slides](lectures/10-5_Class_Performance.pdf)

[Lecture Video](https://ensemble.reed.edu/Watch/m9ENf75P)

#### Topics
 
- KNN in R

- Assessing model performance for classification

  - [Iris demo from end of class](files/Demo_10-5.html) [(.Rmd)](Demo_10-5.html
Demo_10-5.Rmd)

- [Mushroom Hunting](data/mushrooms.csv)

#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Sections 4.6.1, 4.6.2, 4.6.5 and 4.6.6 (p 154-161, 163 - 167) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)



### Wednesday 10-7

[Lecture Slides](lectures/10-7_LDA.pdf)

[Lecture Video](https://ensemble.reed.edu/Watch/Nk7c2HRy)

#### Topics
 

- Linear Discriminant Analysis

 


#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Section 4.4 (p 138 - 150) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)

*The following reading is suggested for those interested in the mathematics behind LDA and who are familiar with linear algebra*

- Section 12.3 (p 287 - 297) in [Applied Predictive Modeling](https://link-springer-com.proxy.library.reed.edu/book/10.1007%2F978-1-4614-6849-3) 


#### Due

- HW 3


#### Assigned

- HW 4 assigned (Due Wednesday 10/14 by 1:35pm)


### Friday 10-9
 
[Lecture Slides](lectures/10-9_QDA.pdf)

[Lecture Video](https://ensemble.reed.edu/Watch/p5WKa2d4)

#### Topics
 

-  QDA

- Comparison of Classification Methods



#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*


- Read Sections 4.5, 4.6.3, 4.6.4 (p 151 - 154, 161 - 163) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)

*The following reading is suggested for those interested in the mathematics behind QDA and who are familiar with linear algebra*

- Section 13.1 (p 329 - 332) in [Applied Predictive Modeling](https://link-springer-com.proxy.library.reed.edu/book/10.1007%2F978-1-4614-6849-3) 



**********************************************



## Week 7



### Monday 10-12

[Lecture Notes](lectures/10-12_CV.pdf)

[Lecture Video](https://ensemble.reed.edu/Watch/c8E9QzYm)


#### Topics
 
- Cross validation

  - [Penguin Model Google Sheet](https://docs.google.com/spreadsheets/d/1K4sYoF8cTQAtlt8esWU_IepyvyLeIUEyXi1DoVqXRYc/edit?usp=sharing)

- LOOCV 

- k-fold CV


#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Sections 5.1 and 5.3.1 - 5.3.3 (p 175 - 186, 191 - 193) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)

### Wednesday 10-14
 
[Lecture Notes](lectures/10-14_CV_Bias_Variance.pdf)

[Lecture Video](https://ensemble.reed.edu/Watch/b7GQo4c5)

#### Topics
 
- Cross validation

  - [Penguin Model Google Sheet](https://docs.google.com/spreadsheets/d/1K4sYoF8cTQAtlt8esWU_IepyvyLeIUEyXi1DoVqXRYc/edit?usp=sharing)
  
  - [Penguin Group Analysis](files/Resampling_10-12.html) [.Rmd](files/Resampling_10-12.Rmd)

- LOOCV 

- k-fold CV

- Bias-Variance Tradeoff Penguins


#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Sections 5.2 and 5.3.4 (p 187 - 190, 194 - 197) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)

#### Due

- HW 4


#### Assigned

- HW 5 assigned (Due Wednesday 10/21 by 1:35pm)


### Friday 10-16

[Lecture Notes](lectures/10-16_Bootstrap.pdf)

[Lecture Video](https://ensemble.reed.edu/Watch/p5CWm87Q)

#### Topics

- Bias-Variance Tradeoff

  - [Live Code](files/Demo_10-14.html) [.Rmd](files/Demo_10-14.Rmd)
 
- The bootstrap

- Summary of data splitting methods


#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Section 4.3, 4.4, 4.7, 4.8 (p 67 - 73, 77 - 80) in [Applied Predictive Modeling](https://link-springer-com.proxy.library.reed.edu/book/10.1007%2F978-1-4614-6849-3)



**********************************************


## Week 8



### Monday 10-19

[Lecture Slides](lectures/10-19_Subset_Selection.pdf)

[Lecture Video](https://ensemble.reed.edu/Watch/c4MWe26B)

#### Topics
 
- Subset Selection



#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Sections 6.1 and 6.5.1 - 6.5.3 (p 203 - 214, 244 - 250) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)

### Wednesday 10-21
 
[Lecture Slides](lectures/10-21_Penalized_Regression.pdf)

[Lecture Video](https://ensemble.reed.edu/Watch/i9SAs72X)

#### Topics
 
- Penalized Regression


#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Sections 6.2 and 5.3.4 (p 214 - 228, 251 - 255) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)

#### Due

- HW 5


#### Assigned

- None


### Friday 10-23

 

#### Topics

- Midterm 2 Review

#### Reading Assignment

- None



**********************************************


## Week 9



### Monday 10-26


No class.

### Wednesday 10-28

[Lecture Slides](lectures/10-28_Ridge_Regression.pdf)

[Lecture Video](https://ensemble.reed.edu/Watch/Mc45GfFe)

#### Topics
 
- Ridge Regression

- Group projects


#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Reread Sections 6.2 and 5.3.4 (p 214 - 228, 251 - 255) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)

#### Due

- None


#### Assigned

- Revisions to Midterm 1 model (due Wednesday 11/4 by 1:35 pm); details forthcoming


### Friday 10-30

[Lecture Notes](lectures/10-30_LASSO.pdf)

[Lecture Video](https://ensemble.reed.edu/Watch/i3K9RmPs)

#### Topics

- LASSO

- Group Projects

#### Reading Assignment

- Section 6.4 (p 124 - 128) in [Applied Predictive Modeling](https://link-springer-com.proxy.library.reed.edu/book/10.1007%2F978-1-4614-6849-3)

**********************************************


## Week 10



### Monday 11-2

[Lecture Notes](lectures/11-2_Trees.pdf)

[Lecture Video](https://ensemble.reed.edu/Watch/a8F5TqQf)

#### Topics
 
- Regression Trees

  - [Mtcars regression tree](img/mtplot.png)


#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Section 8.1 (p 301 - 316) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)
 

### Wednesday 11-4

[Lecture Notes](lectures/11-4_Trees_2.pdf)

[Lecture Video](https://ensemble.reed.edu/Watch/t5YKg26L)

#### Topics
 
- Classification Trees


#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Section 8.1, 8.8 (just the part on Single Trees) and 14.8 (just the part on Classification trees) (p 175 - 184, 212 - 214, 402 - 405) in [Applied Predictive Modeling](https://link-springer-com.proxy.library.reed.edu/book/10.1007%2F978-1-4614-6849-3) 

#### Due

- HW 6


#### Assigned

- HW 7


### Friday 11-6

[Lecture Notes](lectures/11-6_Trees_3.pdf)

[Lecture Video](https://ensemble.reed.edu/Watch/Zc87Czk9)

#### Topics

- Classification Trees

  - [Classification Tree Activity](files/class-tree-activity.pdf)

#### Reading Assignment

- Section 8.2.1 (p 316 - 319) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)


**************************************************

## Week 11



### Monday 11-9

[Lecture Notes](lectures/11-9_Bagging.pdf)

[Lecture Video](https://ensemble.reed.edu/Watch/Xa2j7LYf)

#### Topics
 
- Bagging and Random Forests Trees




#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Section 8.2  (p 316 - 324) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)





### Wednesday 11-11

[Lecture Notes](lectures/11-11_Boosting.pdf) 

[Lecture Video](https://ensemble.reed.edu/Watch/x9W4Yrg7)

#### Topics
 
- Boosting for Classification and Regression




#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Section 8.2, 8.3.3 - 8.3.4  (p 316 - 324, 328 - 331) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)


#### Due

- HW 7


#### Assigned

- HW 8


### Friday 11-13

[Lecture Notes](lectures/11-13_Model_Trees.pdf) 


#### Topics
 
- Model Trees




#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- TBA


**************************************************

## Week 12



### Monday 11-16

[Lecture Notes](lectures/11-16_PCR.pdf) 
[Lecture Video](https://ensemble.reed.edu/Watch/g2BKa83L)

#### Topics
 
- Principal Component Regression




#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Section 10.1 - 10.2  (p 373 - 384) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)





### Wednesday 11-18

[Lecture Notes](lectures/11-18_PCA.pdf) 
[Lecture Video](https://ensemble.reed.edu/Watch/Fc3p6NKr)

#### Topics
 
- More PCA




#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Section 10.4  (p 401 - 404) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)


#### Due

- HW 8


#### Assigned

- None


### Friday 11-20

[Lecture Video](https://ensemble.reed.edu/Watch/i2M8WrGk) 

#### Topics
 
- PCA in R




#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- None

**************************************************

## Week 13


### Monday 11-30


[Lecture Notes](lectures/11-30_Tidymodels.pdf) 

[Lecture Video](https://ensemble.reed.edu/Watch/Ck47QnKx)


#### Topics
 
- tidymodels




#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Skim Chapters 4 and 7 in [Tidy Modeling with R](https://www.tmwr.org/)





### Wednesday 12-2

[Lecture Notes](lectures/12-2_Tidymodels_II.pdf) 

[Lecture Video](https://ensemble.reed.edu/Watch/Tw74DcYs)

#### Topics
 
- More tidymodels




#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Skim Chapters 6, 8 and 9 in [Tidy Modeling with R](https://www.tmwr.org/) 


#### Due

- None


#### Assigned

- None


### Friday 12-4

[Lecture Notes](lectures/12-4_Tidymodels_III.pdf) 

[Lecture Video](https://ensemble.reed.edu/Watch/i3D8SgRe)

#### Topics
 
-  Review




#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- None


********************************************************************


## Week 14


### Monday 12-7


[Lecture Notes](lectures/12-7_Stacks.pdf) 

[Lecture Video](https://ensemble.reed.edu/Watch/i5H2Nfm9)


#### Topics
 
- `stacks`



#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- The `stacks` [vignette](https://stacks.tidymodels.org/articles/basics.html)


********************************************************************


## Week 15


### Monday 12-14



 


#### Topics
 
- Presentations 9am to Noon



#### Reading Assignment

- None